SCREEN_WIDTH = 720
SCREEN_HEIGHT = 720
GAME_SCREEN_LEFT = int(SCREEN_WIDTH / 5)
GAME_SCREEN_RIGHT  =int(4*SCREEN_WIDTH / 5)

FPS = 60

SCORE_FONT = 'graphics\\SpecialElite.ttf'
TITLE_FONT = 'graphics\\Fancy.ttf'
TITLE_FONT_SIZE = 100
TITLE_TEXT_COLOR = 'white'
TITLE_COLOR = 'steelblue4'
BORDER_COLOR = 'aquamarine'